### ISSUE TITLE
Addon Vehicle/Keys

### ISSUE THREAD

**Issue by chewbacca2607** [xabier1989/WiredPlayers-RP#22]
First of all: Great Work man :D 
I have three Issues 
First, I couldn't figure out how to add addon vehicles to my game (I'm using a VPS)
Second, how do I get the keys to a vehicle? When I buy a vehicle or even create an new one it says that I'm not the owner of that vehicle, so I can't park it :/
My last question/issue is: How can I add gas stations? 
<3

**Comment by RivaldisR** [comment]
Hey @chewbacca2607 did you managed to run server on vps ?

**Comment by sing4pur** [comment]
@chewbacca2607  You can give the keys to the car as the chief of the police station, but you will not be able to park the car because, in my opinion, the commands have not been completed. Gas station creates as an admin command "create business 12" if I remember well, thank fuel command /refuel, do not use "F" when you are at a gas station. There is some error in the parameters, you will find yourself in the market..24/7.

**Comment by xabier1989** [comment]
About the add-on vehicles, check on the forums/Discord, not related to the gamemode.

You can set the owner of the vehicle so that player has the keys of the car, if you want to lend your car keys to another player, just use /keys command.

About the gas stations, as @sing4pur said you have to create the business and use /refuel near to the text label. The 24/7 interior for the gas station is done on purpose, is not an error.
